<head>
  <link rel="stylesheet" type="text/css" href="/css/modifiemoncompte.css">
</head>
<div class="entete"
<p>Bienvenue $user</p>
<div class="datte">
<p>nous sommes le $date il est $heure</p>
<p>votre derniere connexion il y a x jours</p>
</div>
</div>

<div class="cadre">

<h3>Modifier Mon compte</h3>

<div class="moncompte">

  <div class="left">
    <div class="col1">
    <p>Nom</p>
    <p>Prenom</p>
    <p>Password</p>
    <p>Email</p>
    </div>
  <div class="col2">
    <input type="text" placeholder="$nom">
    <input type="text" placeholder="$prenom">
    <input type="text" placeholder="$password">
    <input type="text" placeholder="$Email">
  </div>
  </div>
  <div class="right">
    <div class="col3">
    <p>Adresse</p>
    <p>Ville</p>
    <p>Code Postal</p>
    <p>Tel</p>
    <p>Mobile</p>
    </div>
  <div class="col4">
    <input type="text" placeholder="$Adresse">
    <input type="text" placeholder="$Ville">
    <input type="text" placeholder="$CodePosta">
    <input type="text" placeholder="$tel">
    <input type="text" placeholder="$mobile">
  </div>
  </div>
  </div>
  <div id="bouton">
<input type="button" value="Modifier mes infos" href="lien"/>
</div>
</div>
