  <link rel="stylesheet" type="text/css" href="/css/accueil.css">
  <div class="boutontop">

    <form method="POST" action="/application/creer/index">
      <input type="submit" name="Creer" value="Creer une anonce" class="boutoncreer">
    </form>


      <!--<input type="button" value="Rechercher autour de moi" href="lien" id="topright"/>-->
    </div>
<div class="cadre">
  <h3>Recherche</h3>
<input type="text" placeholder="Rechercher" id="search"/>
<div class="listes">

<form method="post">
	<select name="theme" size="1">
			<option value="0">theme</option>
			<option value="1">voiture</option>
			<option value="2">velo</option>
			<option value="3">moto</option>
		</select>

    <select name="catégorie" size="1">
  			<option value="0">catégorie</option>
  			<option value="1">Neuf</option>
  			<option value="2">Occasion</option>
  			<option value="3">Piéces détachées</option>
  		</select>

      <select name="region" size="1">
          <option value="0">region</option>
          <option value="1">region1</option>
          <option value="2">region2</option>
          <option value="3">region3</option>
        </select>

<input type="number" placeholder="Prix"/>

</div>
<div>
<input type="checkbox" name="Typean[]" value="Demande" />
<label for="IdCheckBox">Demande</label>
<input type="checkbox" name="Typean[]" value="Offre" />
<label for="IdCheckBox">Offre</label>
<input type="checkbox" name="Type[]" value="Particuler" />
<label for="IdCheckBox">Particulier</label>
<input type="checkbox" name="Type[]" value="Professionel" />
<label for="IdCheckBox">Professionnel</label>
</div>
<div>
<input type="submit" name="submit">
</form>
</div>
</div>
<div class="last">
  <h4>Les dernières anonces</h4>
  <div class="offres">
<div>
  <div class="page">
      <div class="col1">


        <h5>Offre</h5>
        <h1>Titre</h1>


        <img src="http://placehold.it/100x100">
        <div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="false">
</div>
        </div>
      <div class="mainanonce">

        <h3>Description du produit:</h3>
        <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius </p>

        <div class="bouton">
       <form method="POST" action="/application/annonces/index">
         <input type="submit" name="voir" value="Voir l'annonce">
       </form>
     </div>
      </div>
      <div class="col2">
        <h2>prix</h2>
        <p>Béziers</p>

      </div>
  </div>
</div>

<div>
  <div class="page">
      <div class="col1">
        <h5>Offre</h5>
        <h1>Titre</h1>


        <img src="http://placehold.it/100x100">
        </div>
      <div class="mainanonce">

        <h3>Description du produit:</h3>
        <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius </p>
        <div class="bouton">
       <form method="POST" action="/application/contactv/index">
         <input type="submit" name="voir" value="Voir l'anonce">
       </form>
     </div>
      </div>
      <div class="col2">
        <h2>prix</h2>
        <p>Béziers</p>

      </div>
  </div>
</div>
<div>
  <div class="page">
      <div class="col1">
        <h5>Offre</h5>
        <h1>Titre</h1>


        <img src="http://placehold.it/100x100">
        </div>
      <div class="mainanonce">

        <h3>Description du produit:</h3>
        <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius </p>
        <div class="bouton">
       <form method="POST" action="/application/contactv/index">
         <input type="submit" name="voir" value="Voir l'anonce">
       </form>
     </div>
      </div>
      <div class="col2">
        <h2>prix</h2>
        <p>Béziers</p>

      </div>
  </div>

</div>
</div>

<div>
  <div class="page">
      <div class="col1">
        <h5>Demande</h5>
        <h1>Titre</h1>


        <img src="http://placehold.it/100x100">
        </div>
      <div class="mainanonce">

        <h3>Description du produit:</h3>
        <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius </p>
        <div class="bouton">
       <form method="POST" action="/application/contactv/index">
         <input type="submit" name="voir" value="Voir l'anonce">
       </form>
     </div>
      </div>
      <div class="col2">
        <h2>prix</h2>
        <p>Béziers</p>

      </div>
  </div>
</div><div>
  <div class="page">
      <div class="col1">
        <h5>Demande</h5>
        <h1>Titre</h1>


        <img src="http://placehold.it/100x100">
        </div>
      <div class="mainanonce">

        <h3>Description du produit:</h3>
        <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius </p>
        <div class="bouton">
       <form method="POST" action="/application/contactv/index">
         <input type="submit" name="voir" value="Voir l'anonce">
       </form>
     </div>
      </div>
      <div class="col2">
        <h2>prix</h2>
        <p>Béziers</p>

      </div>
  </div>
</div><div>
  <div class="page">
      <div class="col1">
        <h5>Demande</h5>
        <h1>Titre</h1>


        <img src="http://placehold.it/100x100">
        </div>
      <div class="mainanonce">

        <h3>Description du produit:</h3>
        <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius </p>
        <div class="bouton">
       <form method="POST" action="/application/contactv/index">
         <input type="submit" name="voir" value="Voir l'anonce">
       </form>
     </div>
      </div>
      <div class="col2">
        <h2>prix</h2>
        <p>Béziers</p>

      </div>
  </div>
</div>
</div>
<div class="listesbottom">

    <ul id="lproduit">
      <li>liste de produits les plus recherché</li><br>
      <li><a href="">Produit</a></li>
      <li><a href="">Produit</a></li>
      <li><a href="">Produit</a></li>
      <li><a href="">Produit</a></li>
      <li><a href="">Produit</a></li>
      <li><a href="">Produit</a></li>
      <li><a href="">Produit</a></li>
    </ul>

          <ul id="lcat">
            <li>liste de catégories les plus recherché</li><br>
            <li><a href="">Catégorie</a></li>
            <li><a href="">Catégorie</a></li>
            <li><a href="">Catégorie</a></li>
            <li><a href="">Catégorie</a></li>
            <li><a href="">Catégorie</a></li>
            <li><a href="">Catégorie</a></li>
            <li><a href="">Catégorie</a></li>
          </ul>

          <ul id="lville">
            <li>liste de villes les plus recherché</li><br>
            <li><a href="">Ville</a></li>
            <li><a href="">Ville</a></li>
            <li><a href="">Ville</a></li>
            <li><a href="">Ville</a></li>
            <li><a href="">Ville</a></li>
            <li><a href="">Ville</a></li>
            <li><a href="">Ville</a></li>
          </ul>

          <ul id="ltheme">
            <li>liste de themes les plus recherché</li><br>
            <li><a href="">Theme</a></li>
            <li><a href="">Theme</a></li>
            <li><a href="">Theme</a></li>
            <li><a href="">Theme</a></li>
            <li><a href="">Theme</a></li>
            <li><a href="">Theme</a></li>
            <li><a href="">Theme</a></li>
          </ul>
</div>
