<!DOCTYPE html>
<html>
     <head>
       <title>Le Petit coin Chris</title>
     <meta http-equiv="content-type" content="text/html"; charset="utf-8">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     <link rel="stylesheet" type="text/css" href="public/css/anonce.css">
     <script type="text/javascript" src="http://maps.google.com/maps/api/js"></script>
     <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
     <script type="text/javascript" src="js/jquery-1.4.min.js"></script>
     <script type="text/javascript" language="javascript">
     jQuery.fn.center = function () {
       this.css("margin","auto");
       this.css("top", ( $(window).height() - this.height() ) /2+$(window).scrollTop() + "px");
       this.css("left", ( $(window).width() - this.width() ) /2+$(window).scrollLeft() + "px");
       return this;
     }

     $(document).ready(function() {
       $("#thumbnail img").click(function(e){

         $("#background").css({"opacity" : "0.1"})
                 .fadeIn("slow");

         $("#large").html("<img src='"+$(this).parent(). attr("href")+"' alt='"+$(this).attr("alt")+"' /><br/>"+$(this).attr("rel")+"")
                .center()
                .fadeIn("slow");

         return false;
       });

       $(document).keypress(function(e){
         if(e.keyCode==27){
           $("#background").fadeOut("slow");
           $("#large").fadeOut("slow");
         }
       });

       $("#background").click(function(){
         $("#background").fadeOut("slow");
         $("#large").fadeOut("slow");
       });

       $("#large").click(function(){
         $("#background").fadeOut("slow");
         $("#large").fadeOut("slow");
       });

     });
    </script>
    <style>

     img {
      border: none;
     }
     #thumbnail img {
      cursor: pointer;
     }
     #large {
       float: inherit;
      display: none;
      position: absolute;
      background: #FFFFFF;
      padding: 5px;
      z-index: 10;
      min-height: 200px;
      min-width: 200px;
      color: #336699;
     }
     #background {
      display: none;
      position: absolute;
      overflow: visible;
      height: 100%;
      width: 100%;
      top: 0;
      left: 0;
      background: black;
      z-index: 1;
     }
    nav {
    width: 100%;
    position: fixed;
    z-index: 2;
    top: 0;
    left: 0;
    height: 50px;
    background-color: yellow;
    text-align: right;
    line-height: 40px;
    padding-right: 5px;
    border: 1px solid black; }
    nav a:last-child {
    border-right: hidden;
    border-left: 1px solid black; }
    nav a:nth-child(5) {
    visibility: hidden; }
    nav a {
    text-decoration: none;
    font-size: 30px;
    color: #000;
    border-right: 1px solid black;
    padding: 0px 10px;
    margin: auto; }

    .page {
    margin: 100px auto;
    display: flex;
    flex: wrap;
    border: 1px solid black;
    width: 80%;
    position: relative;
    border-radius: 5px; }
    .page .col1 {
    padding-bottom: 10px;
    padding-left: 5px;
    width: 21%; }
    .page .col1 h5 {
    position: absolute;
    top: -20px;
    background: #fff;
    left: 10px;
    padding: 0 5px; }
    .page h1 {
    white-space: nowrap; }

    .mainanonce {
    padding-left: 15px;
    width: 70%; }
    .mainanonce h3 {
    margin-top: 135px; }
    .mainanonce .bouton {
    white-space: nowrap;
    bottom: 0;
    direction: rtl;
    float: right;
    margin-top: 20px; }

    .col2 {
    position: absolute;
    right: 0;
    padding-right: 10px;
    width: 10%;
    text-align: right; }
    .col2 h6 {
    direction: rtl;
    white-space: nowrap; }
    .col2 h2 {
    direction: rtl; }
    .col2 p {
    white-space: nowrap;
    direction: rtl; }

    footer {
    color: lightgrey;
    width: 80%;
    text-align: center;
    margin: auto;
    font-size: 10px; }

    /*# sourceMappingURL=anonce.css.map */

     </style>
   </head>
     <body>

        <div id="background"></div>
     <section>
       <div class="page">

           <div class="col1">
             <h5>Anonce</h5>
             <h1>Titre</h1>
             <p>Theme</p>
             <p>Catégorie</p>
              <div align="center">

                <div id="thumbnail">
                <h3>Click on the image</h3>
                <a href="images/hills.jpg"><img src="images/thumbnails/hills-thumb.jpg" alt="hills" rel="Hills Image" /></a>
                <a href="images/lilies.jpg"><img src="images/thumbnails/lilies-thumb.jpg" alt="lilies" rel="Lilies Image" /></a>
                <a href="images/sunset.jpg"><img src="images/thumbnails/sunset-thumb.jpg" alt="sunset" rel="Sunset Image" /></a>
                <a href="images/winter.jpg"><img src="images/thumbnails/winter-thumb.jpg" alt="winter" rel="Winter Image" /></a>
                <p id="large"></p>
                </div>
                <div id="large"></div>

             </div>
           </div>


           <div class="mainanonce">
             <h3>Description du produit:</h3>
             <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius est propter qui et diligamus duobus ab ad imperio est Pyrrho in aliqua propter quos M' Cum quos est quodam et semper Sp duobus modo vidimus ad propter non etiam decertatum aliqua Superbum virtutem alienos numquam quis animos benevola virtutem magis diligamus ab imperio viderit qui propter Pyrrho.</p>
             <button type="button" name="button" class="bouton">Contacter le vendeur</button>
           </div>
           <div class="col2">
             <h6>date de depot</h6>
             <h2>prix</h2>
             <?php
             $sql = 'SELECT * FROM cpostal';
             $req = $pdo->query($sql);
             while($row = $req->fetch()) {
             echo '<a href=""-'.$row['id'].'.html">'.$row['cpostal'].'</a><br/>';
             }
             $req->closeCursor();
?>





           </div>

       </div>
     </section>

<div id="map_canvas"></div>
</body>
</html>
