<link rel="stylesheet" type="text/css" href="/css/creer.css">

<section class="page">
  <div class="part1">
    <img src="/img/canard_720.jpg" alt="">
  </div>

  <div class="part2">

  <div class="col1">
       <input type="text" name="inti" id="intitule" placeholder="Intitulé" size="55" />
        <FORM>
        <select name="theme">
        <option value="Theme">THEME</option>
        <OPTION>theme1
        <OPTION>theme2
        <OPTION>theme3
        <OPTION>theme4
        <OPTION>theme5
        </SELECT>




      <select name="catégorie">
      <option value="Catégorie">CATEGORIE</option>
      <OPTION>Catégorie1
      <OPTION>Catégorie2
      <OPTION>Catégorie3
      <OPTION>Catégorie4
      <OPTION>Catégorie5
      <OPTION>Catégorie6
      </SELECT>
      <input type="text" name="prix" id="prix" placeholder="Prix" />
    </FORM>
      <textarea name="descritption" rows="15" cols="85"></textarea>
      <input type="checkbox" id="checkbox1" value="pro">
      <label for="checkbox1">Pro</label>
      <input type="checkbox" id="checkbox2" value="particulier">
      <label for="checkbox2">Particulier</label><br>
      <button type="button" name="button" class="bouton" id="valid">Valider</button>
</div>

  <div class="col2">
    <div class="cb3">
      <input type="checkbox" id="checkbox3" value="particulier">
      <label for="checkbox3">Offre</label>
    </div>
    <div class="cb4">
      <input type="checkbox" id="checkbox4" value="particulier">
      <label for="checkbox4">Demande</label>
    </div>
<div class="photo">
    <button type="button" name="button" class="bouton">photo1</button>
    <button type="button" name="button" class="bouton">photo2</button>
    <button type="button" name="button" class="bouton">photo3</button>
</div>
  </div>
</div>

</section>
