<!DOCTYPE html>
<html>
     <head>
     <meta http-equiv="content-type" content="text/html"; charset="utf-8">
     <link rel="stylesheet" type="text/css" href="/css/anonce.css">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     </head>
     <body>
     <section>
       <div class="page">
           <div class="col1">
             <h5>Anonce</h5>
             <h1>Titre</h1>
             <p>Theme</p>
             <p>Catégorie</p>
             <p>Demande</p>
             <img class="thumbnail" src="http://placehold.it/200x200"></img>
             <img src="http://placehold.it/100x100"></img>
             <img src="http://placehold.it/100x100"></img>
           </div>
           <div class="mainanonce">
             <h3>Description du produit:</h3>
             <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius est propter qui et diligamus duobus ab ad imperio est Pyrrho in aliqua propter quos M' Cum quos est quodam et semper Sp duobus modo vidimus ad propter non etiam decertatum aliqua Superbum virtutem alienos numquam quis animos benevola virtutem magis diligamus ab imperio viderit qui propter Pyrrho.</p>
             <form method="POST" action="/application/contactv/index">
               <input type="submit" name="Concact" value="Contacter le vendeur" class="bouton">
             </form>
           </div>
           <div class="col2">
             <h6>date de depot</h6>
             <h2>prix</h2>
             <p>Béziers</br>34500</p>
           </div>
       </div>
     </section>
</body>
</html>
