<html>
<head>
  <title>Le Petit coin</title>
<meta http-equiv="content-type" content="text/html"; charset="utf-8">
<link rel="stylesheet" type="text/css" href="/css/login.css">
<script type="text/javascript" src="/js/afficher_cacher_div.js"></script>

</head>
<body>



<div class="page">
<div class="creercompte">
<h2>Créer compte</h2>


     <script type="text/javascript">
     //<!--
         afficher_cacher('texte');
     //-->
     </script>




<form method="post">
  <div class="ins">
    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    <input type="text" name="name" placeholder="User Name">
  </div>

  <div class="ins">
    <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
    <input type="text" name="email" placeholder="@mail" >
  </div>

  <div class="ins">
    <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
    <input type="password" name="pass" placeholder="password"></br>
  </div>

  <div class="ins">
    <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
    <input type="text" name="tel" placeholder="Phone">
  </div>

  <div class="ins">
    <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
    <input type="text" name="Ville" placeholder="Ville">
  </div>

  <div class="ins">
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    <input type="text" name="cpostal" placeholder="Code postal"></br>
  </div>
<!--<input type="text" name="Month" placeholder="Month">
<input type="text" name="Year" placeholder="Year"></br>

<select name="date">
<option value="DATE">DATE</option>
<option value="01">01</option>
<option value="02">02</option>
<option value="03">03</option>
<option value="04">04</option>
<option value="05">05</option>
<option value="06">06</option>
<option value="07">07</option>
<option value="08">08</option>
<option value="09">09</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select>
<select name="month">
<option value="MONTH">MONTH</option>
<option value="JAN">JANVIER</option>
<option value="FEV">FEVRIER</option>
<option value="MAR">MARS</option>
<option value="AVR">AVRIL</option>
<option value="MAI">MAI</option>
<option value="JUI">JUIN</option>
<option value="JUIL">JUILLET</option>
<option value="AOU">AOUT</option>
<option value="SEP">SEPTEMBRE</option>
<option value="OCT">OCTOBRE</option>
<option value="NOV">NOVEMBRE</option>
<option value="DEC">DECEMBRE</option>
</select>
<select name="year">
<option value="YEAR">YEAR</option>
<option value="2016">2016</option>
<option value="2015">2015</option>
<option value="2014">2014</option>
<option value="2013">2013</option>
<option value="2012">2012</option>
<option value="2011">2011</option>
<option value="2010">2010</option>
<option value="2009">2009</option>
<option value="2008">2008</option>
<option value="2007">2007</option>
<option value="2006">2006</option>
<option value="2005">2005</option>
<option value="2004">2004</option>
<option value="2003">2003</option>
<option value="2002">2002</option>
<option value="2001">2001</option>
<option value="2000">2000</option>
<option value="1999">1999</option>
<option value="1998">1998</option>
<option value="1997">1997</option>
<option value="1996">1996</option>
<option value="1995">1995</option>
<option value="1994">1994</option>
<option value="1993">1993</option>
<option value="1992">1992</option>
<option value="1991">1991</option>
<option value="1990">1990</option>
<option value="1989">1989</option>
<option value="1988">1988</option>
<option value="1987">1987</option>
<option value="1986">1986</option>
<option value="1985">1985</option>
<option value="1984">1984</option>
<option value="1983">1983</option>
<option value="1982">1982</option>
<option value="1981">1981</option>
<option value="1980">1980</option>
<option value="1979">1979</option>
<option value="1978">1978</option>
<option value="1977">1977</option>
<option value="1976">1976</option>
<option value="1975">1975</option>
<option value="1974">1974</option>
<option value="1973">1973</option>
<option value="1972">1972</option>
<option value="1971">Vous êtes trop vieux</option>



</select><br><br> -->


<input type="submit" name="signup" value="VALIDER" class="bouton">
</form>
</div>
<!-- <div style="width:500px ; float:right; height:600px;"> -->
<div class="connexion">
<h2>Connexion</h2>


   <script type="text/javascript">
   //<!--
       afficher_cacher('texte2');
   //-->
   </script>
<form method="post" action="profile">

<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
<input type="text" name="email" placeholder="example@example.com" class="input1">

<span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
<input type="password" name="pass" placeholder="**********" class="input1">

<input type="submit"  name="signin" value="Connexion" class="input1" >
</form>
</div>
</div>
</body>
</html>
