<link rel="stylesheet" type="text/css" href="/css/admin.css">

<div class="liste_des_utilisateurs">
  <h2>Liste des utilisteurs</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nom</th>
        <th>Prénom</th>
        <th>inscription</th>
        <th>Catégorie</th>
        <th>Status</th>
        <th>Modifier</th>
        <th>Supprimer</th>
      </thead>
      <tbody>
      <tr>
        <td>Jean</td>
        <td>Jean</td>
        <td>01/01/2000</td>
        <td>Particulier</td>
        <td>$online</td>
        <td>modifier</td>
        <td>supprimer</td>
      </tr>
    </tbody>
  </table>
</div>
<div>
  <h2>Liste des annonces</h2>
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Titre</th>
      <th>Date</th>
      <th>Theme</th>
      <th>Description</th>
      <th>En ligne</th>
      <th>Modifier</th>
      <th>Supprimer</th>
    </thead>
      <tbody>
        <tr>
          <td>Guitare</td>
          <td>07/12/2000</td>
          <td>Musique</td>
          <td>Blablabla</td>
          <td>oui</td>
          <td>Modifier</td>
          <td>Supprimer</td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="table catégorie">
  <h2>Gestion des thèmes et catégories</h2>
    <input type="button" value="Ajouter un thème" href="lien"/>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Thème</th>
          <th>Catégorie</th>
          <th>Modifier</th>
          <th>Supprimer</th>
        </tr>
      </thead>
        <tbody>
          <tr>
            <td>Loisirs</td>
            <td>Musique</td>
            <td>modifier</td>
            <td>Supprimer</td>
          </tr>
        </tbody>
      </table>
    </div>
