<head>
  <link rel="stylesheet" type="text/css" href="/css/mncpt.css">
</head>
<div class="entete"
<p>Bienvenue $user</p>
<div class="datte">
<p>nous sommes le $date il est $heure</p>
<p>votre derniere connexion il y a x jours</p>
<input type="button" value="Creer une offre" href="lien"/>
</div>
</div>

<div class="cadre">

<h3>Mon compte</h3>

<div class="moncompte">

  <div class="left">
    <div class="col1">
    <p>Nom</p>
    <p>Prenom</p>
    <p>Password</p>
    <p>Email</p>
    <p>Inscrit Depuis</p>
    </div>
  <div class="col2">
    <p>$nom</p>
    <p>$prenom</p>
    <p>$password</p>
    <p>$email</p>
    <p>$date_inscritpion</p>
  </div>
  </div>
  <div class="right">
    <div class="col3">
    <p>Adresse</p>
    <p>Ville</p>
    <p>Code Postal</p>
    <p>Tel</p>
    <p>Mobile</p>
    </div>
  <div class="col4">
    <p>$adresse</p>
    <p>$ville</p>
    <p>$codepostal</p>
    <p>$tel</p>
    <p>$mobile</p>
  </div>
  </div>
  </div>
  <div id="bouton">
<input type="button" value="Modifier mes infos" href="lien"/>
</div>
</div>
<div class="mes annonces">
  <h4>Mes annonces</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Titre</th>
        <th>Date</th>
        <th>Theme</th>
        <th>Description</th>
        <th>En ligne</th>
        <th>Modifier</th>
        <th>Supprimer</th>
        <tbody>
          <tr>
            <td>$Titre</td>
            <td>$date</td>
            <td>$theme</td>
            <td>$description</td>
            <td>$online</td>
            <td>Modifier</td>
            <td>Supprimer</td>
          </tr>
        </tbody>
      </table>
