<!DOCTYPE html>
<html>
     <head>
    <link rel="stylesheet" type="text/css" href="/css/contactv.css">
    <link rel="stylesheet" type="text/css" href="/css/creer.css">
     </head>
     <body>
     <section>
       <div class="container">
         <div class="cot1">
           <p>Le Vendeur: </p>
             <div>
             <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
             <p>Pseudo: $Pseudo_du_vendeur</p>
           </div>

            <div>
              <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
              <p>Email: $Email_du_vendeur</p>
            </div>

            <div>
              <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
              <p>Numero: Numero du vendeur</p>
            </div>

            <div>
              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
              <p>Ville:$ville_du_vendeur</p>
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
              <p>Code postal:$code_postal</p>
            </div>
          </div>
          <div class="cot2">
            <div>
              <p>Envoyer un message au  vendeur : </p>
              <textarea name="descritption" rows="15" cols="85"></textarea>
              <button type="button" name="button">Envoyer</button>
            </div>
          </div>
        </div>
     </section>

</html>
