<!DOCTYPE html>
<html>
     <head>
     <meta http-equiv="content-type" content="text/html"; charset="utf-8">
     <link rel="stylesheet" type="text/css" href="/css/offre.css">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
     </head>
     <body>
     <section>
       <div class="page">
           <div class="col1">
             <h5>Offre</h5>
             <h1>Titre</h1>


             <img src="http://placehold.it/100x100"></img>
             </div>
           <div class="mainanonce">

             <h3>Description du produit:</h3>
             <p> Imperio imperio nimis ab Sp numquam Superbum ab numquam aliqua et oderit Curi memoriam viderit ducibus autem Superbum nimis Sp aliqua alienos quod propter crudelitatem cum Superbum civitas Italia oderit imperio quodam alienos quodam Tarquinium alterum viderit numquam non in Sp habemus Quis probitatem semper etiam quos Quis Sp nihil in eius </p>

           </div>
           <div class="col2">
             <h2>prix</h2>
             <p>Béziers</br>34500</p>
             <div class="bouton">
            <form method="POST" action="/application/contactv/index">
              <input type="submit" name="voir" value="Voir l'anonce">
            </form>
          </div>
           </div>
       </div>
     </section>
</body>
</html>
